language: php
php:
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls; fi;'
