language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then
      phpenv config-rm xdebug.ini;
    fi;
  - composer install --prefer-source --no-interaction

script: phpunit

after_success:
  - vendor/bin/coveralls
